# Generated by Django 3.0.5 on 2020-06-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketingmessage',
            options={'ordering': ['-start_date', '-end_date']},
        ),
        migrations.AlterField(
            model_name='marketingmessage',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
