# Generated by Django 3.0.5 on 2020-05-18 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
