# Generated by Django 3.0.5 on 2020-05-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='gst',
            field=models.IntegerField(default=0),
        ),
    ]
