# Generated by Django 3.0.5 on 2020-06-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_viewimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
