# Generated by Django 3.0.5 on 2020-06-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200606_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='desc',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
