# Generated by Django 3.0.5 on 2020-06-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200606_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewimage',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='viewimage',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='viewimage',
            name='thumbnail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='viewimage',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
