# Generated by Django 3.0.5 on 2020-06-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
