# Generated by Django 3.0.5 on 2020-06-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_contact_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Started', 'Started'), ('Cancled', 'Cancled'), ('Finished', 'Finished')], default='Started', max_length=120),
        ),
    ]
