# Generated by Django 3.0.5 on 2020-06-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20200619_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='special',
            field=models.TextField(default=10, max_length=5000),
        ),
    ]
