# Generated by Django 3.1.3 on 2021-01-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_orders_special'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='sale_price',
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='shop/images/NIL.png', upload_to='shop/images'),
        ),
        migrations.AlterField(
            model_name='viewimage',
            name='viewimage',
            field=models.ImageField(default='shop/images/NIL.png', upload_to='shop/images'),
        ),
    ]
