# Generated by Django 3.1.3 on 2021-01-03 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210104_0019'),
        ('shop', '0018_auto_20210103_2338'),
    ]

    operations = [
    ]
